name: C/C++ Linux CI

on:
  push:
    branches: [ test-github-actions ]
  pull_request:
    branches: [ test-github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd Autotoencoder/Builds/LinuxMakefile
           make CONFIG=Release
