name: C/C++ Linux CI

on:
  push:
    branches: [ test-github-actions ]
  pull_request:
    branches: [ test-github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: install dependencies
      run: sudo apt-get install alsa alsa-tools libcurl4-openssl-dev libwebkit2gtk-4.0-dev libgtk-3-dev
    - name: make
      working-directory: ./AutoencoderJuce/Builds/LinuxMakefile
      run: make CONFIG=Release
